name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install # Optional: Adjust based on your project setup
      - run: npm run build # Optional: Adjust based on your project setup
      - run: |
          npx firebase-tools deploy --only hosting \
          --token ${{ secrets.FIREBASE_TOKEN }}
